# Site language
lang: en-US

# Site title
title: "Lynn Le"

# A description of your site for meta tag, search engine results.
description: "Multidisciplinary AI engineer"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""  # Make sure baseurl is empty if you're deploying to the root

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://lynnle.com"  # Update this to your live site URL

# Favicon
favicon: /assets/img/favicon.ico  # Ensure this path is correct

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a URL.
navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects/
  - text: Blog
    url: /blog/

# The shortname for your Disqus site to enable comments.
disqus: lynnle

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Lynn Le. All rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 3
paginate_path: '/page:num/'

# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
